// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/home_tab_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:frontend/models/models.dart' as _i2;
import 'package:frontend/services/api_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeJobRole_1 extends _i1.SmartFake implements _i2.JobRole {
  _FakeJobRole_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeShiftDefinition_2 extends _i1.SmartFake
    implements _i2.ShiftDefinition {
  _FakeShiftDefinition_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserStats_3 extends _i1.SmartFake implements _i2.UserStats {
  _FakeUserStats_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDashboardHome_4 extends _i1.SmartFake implements _i2.DashboardHome {
  _FakeDashboardHome_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i3.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i5.Future<String> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i5.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#login, [email, password]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String> register(
    String? username,
    String? password,
    String? fullName,
    String? roleSystem, {
    String? managerPin,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #register,
              [username, password, fullName, roleSystem],
              {#managerPin: managerPin},
            ),
            returnValue: _i5.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(
                  #register,
                  [username, password, fullName, roleSystem],
                  {#managerPin: managerPin},
                ),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<_i2.User> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i5.Future<_i2.User>.value(
              _FakeUser_0(this, Invocation.method(#getCurrentUser, [])),
            ),
          )
          as _i5.Future<_i2.User>);

  @override
  _i5.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> changePassword(String? oldPassword, String? newPassword) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [oldPassword, newPassword]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.JobRole>> getRoles() =>
      (super.noSuchMethod(
            Invocation.method(#getRoles, []),
            returnValue: _i5.Future<List<_i2.JobRole>>.value(<_i2.JobRole>[]),
          )
          as _i5.Future<List<_i2.JobRole>>);

  @override
  _i5.Future<_i2.JobRole> createRole(String? name, String? colorHex) =>
      (super.noSuchMethod(
            Invocation.method(#createRole, [name, colorHex]),
            returnValue: _i5.Future<_i2.JobRole>.value(
              _FakeJobRole_1(
                this,
                Invocation.method(#createRole, [name, colorHex]),
              ),
            ),
          )
          as _i5.Future<_i2.JobRole>);

  @override
  _i5.Future<List<_i2.ShiftDefinition>> getShifts() =>
      (super.noSuchMethod(
            Invocation.method(#getShifts, []),
            returnValue: _i5.Future<List<_i2.ShiftDefinition>>.value(
              <_i2.ShiftDefinition>[],
            ),
          )
          as _i5.Future<List<_i2.ShiftDefinition>>);

  @override
  _i5.Future<_i2.ShiftDefinition> createShift(
    String? name,
    String? startTime,
    String? endTime, {
    List<int>? applicableDays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createShift,
              [name, startTime, endTime],
              {#applicableDays: applicableDays},
            ),
            returnValue: _i5.Future<_i2.ShiftDefinition>.value(
              _FakeShiftDefinition_2(
                this,
                Invocation.method(
                  #createShift,
                  [name, startTime, endTime],
                  {#applicableDays: applicableDays},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.ShiftDefinition>);

  @override
  _i5.Future<List<_i2.Availability>> getAvailability(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAvailability, [startDate, endDate]),
            returnValue: _i5.Future<List<_i2.Availability>>.value(
              <_i2.Availability>[],
            ),
          )
          as _i5.Future<List<_i2.Availability>>);

  @override
  _i5.Future<void> updateAvailability(List<_i2.AvailabilityUpdate>? updates) =>
      (super.noSuchMethod(
            Invocation.method(#updateAvailability, [updates]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>> generateSchedule(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#generateSchedule, [startDate, endDate]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<List<_i2.Requirement>> getRequirements(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getRequirements, [startDate, endDate]),
            returnValue: _i5.Future<List<_i2.Requirement>>.value(
              <_i2.Requirement>[],
            ),
          )
          as _i5.Future<List<_i2.Requirement>>);

  @override
  _i5.Future<void> setRequirements(List<_i2.RequirementUpdate>? requirements) =>
      (super.noSuchMethod(
            Invocation.method(#setRequirements, [requirements]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.ScheduleEntry>> getManagerSchedule(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getManagerSchedule, [startDate, endDate]),
            returnValue: _i5.Future<List<_i2.ScheduleEntry>>.value(
              <_i2.ScheduleEntry>[],
            ),
          )
          as _i5.Future<List<_i2.ScheduleEntry>>);

  @override
  _i5.Future<List<_i2.EmployeeScheduleEntry>> getEmployeeSchedule(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEmployeeSchedule, [startDate, endDate]),
            returnValue: _i5.Future<List<_i2.EmployeeScheduleEntry>>.value(
              <_i2.EmployeeScheduleEntry>[],
            ),
          )
          as _i5.Future<List<_i2.EmployeeScheduleEntry>>);

  @override
  _i5.Future<bool> isLoggedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isLoggedIn, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<List<_i2.TeamMember>> getUsers({bool? includeInactive = false}) =>
      (super.noSuchMethod(
            Invocation.method(#getUsers, [], {
              #includeInactive: includeInactive,
            }),
            returnValue: _i5.Future<List<_i2.TeamMember>>.value(
              <_i2.TeamMember>[],
            ),
          )
          as _i5.Future<List<_i2.TeamMember>>);

  @override
  _i5.Future<void> setUserRoles(String? userId, List<int>? roleIds) =>
      (super.noSuchMethod(
            Invocation.method(#setUserRoles, [userId, roleIds]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> resetUserPassword(String? userId, String? newPassword) =>
      (super.noSuchMethod(
            Invocation.method(#resetUserPassword, [userId, newPassword]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateUser(
    String? userId, {
    String? fullName,
    String? email,
    String? roleSystem,
    int? targetHoursPerMonth,
    int? targetShiftsPerMonth,
    bool? isActive,
    bool? clearTargets = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateUser,
              [userId],
              {
                #fullName: fullName,
                #email: email,
                #roleSystem: roleSystem,
                #targetHoursPerMonth: targetHoursPerMonth,
                #targetShiftsPerMonth: targetShiftsPerMonth,
                #isActive: isActive,
                #clearTargets: clearTargets,
              },
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> createUser({
    required String? username,
    required String? password,
    required String? fullName,
    required String? roleSystem,
    String? email,
    int? targetHoursPerMonth,
    int? targetShiftsPerMonth,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [], {
              #username: username,
              #password: password,
              #fullName: fullName,
              #roleSystem: roleSystem,
              #email: email,
              #targetHoursPerMonth: targetHoursPerMonth,
              #targetShiftsPerMonth: targetShiftsPerMonth,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> createAssignment({
    required DateTime? date,
    required int? shiftDefId,
    required String? userId,
    required int? roleId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createAssignment, [], {
              #date: date,
              #shiftDefId: shiftDefId,
              #userId: userId,
              #roleId: roleId,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteAssignment(String? scheduleId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAssignment, [scheduleId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteRole(int? roleId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRole, [roleId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteShift(int? shiftId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteShift, [shiftId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> saveBatchSchedule(
    DateTime? startDate,
    DateTime? endDate,
    List<_i2.ScheduleEntry>? entries,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveBatchSchedule, [
              startDate,
              endDate,
              entries,
            ]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateRole(int? roleId, String? name, String? colorHex) =>
      (super.noSuchMethod(
            Invocation.method(#updateRole, [roleId, name, colorHex]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateShift(
    int? shiftId,
    String? name,
    String? startTime,
    String? endTime,
    List<int>? applicableDays,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateShift, [
              shiftId,
              name,
              startTime,
              endTime,
              applicableDays,
            ]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>> updateAppSettings(
    Map<String, dynamic>? settings,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateAppSettings, [settings]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<void> registerDeviceToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#registerDeviceToken, [token]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> unregisterDeviceToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#unregisterDeviceToken, [token]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.AppNotification>> getNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#getNotifications, []),
            returnValue: _i5.Future<List<_i2.AppNotification>>.value(
              <_i2.AppNotification>[],
            ),
          )
          as _i5.Future<List<_i2.AppNotification>>);

  @override
  _i5.Future<void> markNotificationRead(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#markNotificationRead, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>> getConfig() =>
      (super.noSuchMethod(
            Invocation.method(#getConfig, []),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<void> saveConfig(
    String? name,
    String? openingHours,
    String? address,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveConfig, [name, openingHours, address]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.TeamAvailability>> getTeamAvailability(
    DateTime? weekStart,
    DateTime? weekEnd,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTeamAvailability, [weekStart, weekEnd]),
            returnValue: _i5.Future<List<_i2.TeamAvailability>>.value(
              <_i2.TeamAvailability>[],
            ),
          )
          as _i5.Future<List<_i2.TeamAvailability>>);

  @override
  _i5.Future<Map<String, dynamic>> getAttendanceDefaults(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#getAttendanceDefaults, [date]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> registerAttendance(
    DateTime? date,
    String? checkIn,
    String? checkOut,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#registerAttendance, [date, checkIn, checkOut]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<void> registerManualAttendance({
    required String? userId,
    required DateTime? date,
    required String? checkIn,
    required String? checkOut,
    bool? wasScheduled = true,
    String? status = 'CONFIRMED',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registerManualAttendance, [], {
              #userId: userId,
              #date: date,
              #checkIn: checkIn,
              #checkOut: checkOut,
              #wasScheduled: wasScheduled,
              #status: status,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getMyAttendance(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMyAttendance, [startDate, endDate]),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getPendingAttendance() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingAttendance, []),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<void> confirmAttendance(String? attendanceId) =>
      (super.noSuchMethod(
            Invocation.method(#confirmAttendance, [attendanceId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> rejectAttendance(String? attendanceId) =>
      (super.noSuchMethod(
            Invocation.method(#rejectAttendance, [attendanceId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getAllAttendance(
    DateTime? startDate,
    DateTime? endDate, {
    String? status,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getAllAttendance,
              [startDate, endDate],
              {#status: status},
            ),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<String?> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  String getAttendanceExportUrl(
    DateTime? startDate,
    DateTime? endDate, {
    String? status,
    String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getAttendanceExportUrl,
              [startDate, endDate],
              {#status: status, #token: token},
            ),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(
                #getAttendanceExportUrl,
                [startDate, endDate],
                {#status: status, #token: token},
              ),
            ),
          )
          as String);

  @override
  _i5.Future<List<Map<String, dynamic>>> getEmployeeHours(
    int? month,
    int? year,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEmployeeHours, [month, year]),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<_i2.UserStats> getUserStats(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserStats, [userId]),
            returnValue: _i5.Future<_i2.UserStats>.value(
              _FakeUserStats_3(
                this,
                Invocation.method(#getUserStats, [userId]),
              ),
            ),
          )
          as _i5.Future<_i2.UserStats>);

  @override
  _i5.Future<_i2.DashboardHome> getDashboardHome({DateTime? date}) =>
      (super.noSuchMethod(
            Invocation.method(#getDashboardHome, [], {#date: date}),
            returnValue: _i5.Future<_i2.DashboardHome>.value(
              _FakeDashboardHome_4(
                this,
                Invocation.method(#getDashboardHome, [], {#date: date}),
              ),
            ),
          )
          as _i5.Future<_i2.DashboardHome>);

  @override
  _i5.Future<List<_i2.ShiftGiveaway>> getGiveaways() =>
      (super.noSuchMethod(
            Invocation.method(#getGiveaways, []),
            returnValue: _i5.Future<List<_i2.ShiftGiveaway>>.value(
              <_i2.ShiftGiveaway>[],
            ),
          )
          as _i5.Future<List<_i2.ShiftGiveaway>>);

  @override
  _i5.Future<void> reassignGiveaway(String? giveawayId, String? newUserId) =>
      (super.noSuchMethod(
            Invocation.method(#reassignGiveaway, [giveawayId, newUserId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> cancelGiveaway(String? giveawayId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelGiveaway, [giveawayId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>> submitBugReport({
    required String? title,
    required String? description,
    String? steps = '',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#submitBugReport, [], {
              #title: title,
              #description: description,
              #steps: steps,
            }),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<void> giveAwayShift(String? scheduleId) =>
      (super.noSuchMethod(
            Invocation.method(#giveAwayShift, [scheduleId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>> getGoogleCalendarStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getGoogleCalendarStatus, []),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<void> connectGoogleCalendar(String? authCode) =>
      (super.noSuchMethod(
            Invocation.method(#connectGoogleCalendar, [authCode]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> disconnectGoogleCalendar() =>
      (super.noSuchMethod(
            Invocation.method(#disconnectGoogleCalendar, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.LeaveRequest>> getMyLeaveRequests({String? status}) =>
      (super.noSuchMethod(
            Invocation.method(#getMyLeaveRequests, [], {#status: status}),
            returnValue: _i5.Future<List<_i2.LeaveRequest>>.value(
              <_i2.LeaveRequest>[],
            ),
          )
          as _i5.Future<List<_i2.LeaveRequest>>);

  @override
  _i5.Future<void> createLeaveRequest(
    DateTime? startDate,
    DateTime? endDate,
    String? reason,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createLeaveRequest, [
              startDate,
              endDate,
              reason,
            ]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> cancelLeaveRequest(String? requestId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelLeaveRequest, [requestId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.LeaveRequest>> getAllLeaveRequests({String? status}) =>
      (super.noSuchMethod(
            Invocation.method(#getAllLeaveRequests, [], {#status: status}),
            returnValue: _i5.Future<List<_i2.LeaveRequest>>.value(
              <_i2.LeaveRequest>[],
            ),
          )
          as _i5.Future<List<_i2.LeaveRequest>>);

  @override
  _i5.Future<void> approveLeaveRequest(String? requestId) =>
      (super.noSuchMethod(
            Invocation.method(#approveLeaveRequest, [requestId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> rejectLeaveRequest(String? requestId) =>
      (super.noSuchMethod(
            Invocation.method(#rejectLeaveRequest, [requestId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.LeaveCalendarEntry>> getLeaveCalendar(
    int? year,
    int? month,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLeaveCalendar, [year, month]),
            returnValue: _i5.Future<List<_i2.LeaveCalendarEntry>>.value(
              <_i2.LeaveCalendarEntry>[],
            ),
          )
          as _i5.Future<List<_i2.LeaveCalendarEntry>>);

  @override
  _i5.Future<List<_i2.AvailableEmployee>> getAvailableEmployeesForShift(
    DateTime? date,
    int? shiftDefId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableEmployeesForShift, [
              date,
              shiftDefId,
            ]),
            returnValue: _i5.Future<List<_i2.AvailableEmployee>>.value(
              <_i2.AvailableEmployee>[],
            ),
          )
          as _i5.Future<List<_i2.AvailableEmployee>>);

  @override
  _i5.Future<Map<String, dynamic>> getScheduleSummary({
    required int? year,
    required int? month,
    required DateTime? weekStart,
    required DateTime? weekEnd,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getScheduleSummary, [], {
              #year: year,
              #month: month,
              #weekStart: weekStart,
              #weekEnd: weekEnd,
            }),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getEmployeeGiveaways() =>
      (super.noSuchMethod(
            Invocation.method(#getEmployeeGiveaways, []),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<void> claimGiveaway(String? giveawayId) =>
      (super.noSuchMethod(
            Invocation.method(#claimGiveaway, [giveawayId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
