// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/my_schedule_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dio/dio.dart' as _i2;
import 'package:frontend/models/models.dart' as _i3;
import 'package:frontend/services/api_service.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUser_1 extends _i1.SmartFake implements _i3.User {
  _FakeUser_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeJobRole_2 extends _i1.SmartFake implements _i3.JobRole {
  _FakeJobRole_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeShiftDefinition_3 extends _i1.SmartFake
    implements _i3.ShiftDefinition {
  _FakeShiftDefinition_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserStats_4 extends _i1.SmartFake implements _i3.UserStats {
  _FakeUserStats_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDashboardHome_5 extends _i1.SmartFake implements _i3.DashboardHome {
  _FakeDashboardHome_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRestaurantTable_6 extends _i1.SmartFake
    implements _i3.RestaurantTable {
  _FakeRestaurantTable_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMenuItem_7 extends _i1.SmartFake implements _i3.MenuItem {
  _FakeMenuItem_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeKitchenOrder_8 extends _i1.SmartFake implements _i3.KitchenOrder {
  _FakeKitchenOrder_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTableZone_9 extends _i1.SmartFake implements _i3.TableZone {
  _FakeTableZone_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePosTable_10 extends _i1.SmartFake implements _i3.PosTable {
  _FakePosTable_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePosCategory_11 extends _i1.SmartFake implements _i3.PosCategory {
  _FakePosCategory_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePosMenuItem_12 extends _i1.SmartFake implements _i3.PosMenuItem {
  _FakePosMenuItem_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeModifierGroup_13 extends _i1.SmartFake implements _i3.ModifierGroup {
  _FakeModifierGroup_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePosOrder_14 extends _i1.SmartFake implements _i3.PosOrder {
  _FakePosOrder_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePosOrderItem_15 extends _i1.SmartFake implements _i3.PosOrderItem {
  _FakePosOrderItem_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePosPayment_16 extends _i1.SmartFake implements _i3.PosPayment {
  _FakePosPayment_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTipSummary_17 extends _i1.SmartFake implements _i3.TipSummary {
  _FakeTipSummary_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i4.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i2.Dio get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeDio_0(this, Invocation.getter(#client)),
          )
          as _i2.Dio);

  @override
  _i6.Future<String> login(
    String? email,
    String? password, {
    String? tenantSlug,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #login,
              [email, password],
              {#tenantSlug: tenantSlug},
            ),
            returnValue: _i6.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(
                  #login,
                  [email, password],
                  {#tenantSlug: tenantSlug},
                ),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<String> register(
    String? username,
    String? password,
    String? fullName,
    String? roleSystem, {
    String? managerPin,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #register,
              [username, password, fullName, roleSystem],
              {#managerPin: managerPin},
            ),
            returnValue: _i6.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(
                  #register,
                  [username, password, fullName, roleSystem],
                  {#managerPin: managerPin},
                ),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<_i3.User> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i6.Future<_i3.User>.value(
              _FakeUser_1(this, Invocation.method(#getCurrentUser, [])),
            ),
          )
          as _i6.Future<_i3.User>);

  @override
  _i6.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> changePassword(String? oldPassword, String? newPassword) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [oldPassword, newPassword]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i3.JobRole>> getRoles() =>
      (super.noSuchMethod(
            Invocation.method(#getRoles, []),
            returnValue: _i6.Future<List<_i3.JobRole>>.value(<_i3.JobRole>[]),
          )
          as _i6.Future<List<_i3.JobRole>>);

  @override
  _i6.Future<_i3.JobRole> createRole(String? name, String? colorHex) =>
      (super.noSuchMethod(
            Invocation.method(#createRole, [name, colorHex]),
            returnValue: _i6.Future<_i3.JobRole>.value(
              _FakeJobRole_2(
                this,
                Invocation.method(#createRole, [name, colorHex]),
              ),
            ),
          )
          as _i6.Future<_i3.JobRole>);

  @override
  _i6.Future<List<_i3.ShiftDefinition>> getShifts() =>
      (super.noSuchMethod(
            Invocation.method(#getShifts, []),
            returnValue: _i6.Future<List<_i3.ShiftDefinition>>.value(
              <_i3.ShiftDefinition>[],
            ),
          )
          as _i6.Future<List<_i3.ShiftDefinition>>);

  @override
  _i6.Future<_i3.ShiftDefinition> createShift(
    String? name,
    String? startTime,
    String? endTime, {
    List<int>? applicableDays,
    List<int>? allowedRoleIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createShift,
              [name, startTime, endTime],
              {
                #applicableDays: applicableDays,
                #allowedRoleIds: allowedRoleIds,
              },
            ),
            returnValue: _i6.Future<_i3.ShiftDefinition>.value(
              _FakeShiftDefinition_3(
                this,
                Invocation.method(
                  #createShift,
                  [name, startTime, endTime],
                  {
                    #applicableDays: applicableDays,
                    #allowedRoleIds: allowedRoleIds,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i3.ShiftDefinition>);

  @override
  _i6.Future<List<_i3.Availability>> getAvailability(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAvailability, [startDate, endDate]),
            returnValue: _i6.Future<List<_i3.Availability>>.value(
              <_i3.Availability>[],
            ),
          )
          as _i6.Future<List<_i3.Availability>>);

  @override
  _i6.Future<void> updateAvailability(List<_i3.AvailabilityUpdate>? updates) =>
      (super.noSuchMethod(
            Invocation.method(#updateAvailability, [updates]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<Map<String, dynamic>> generateSchedule(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#generateSchedule, [startDate, endDate]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<List<_i3.Requirement>> getRequirements(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getRequirements, [startDate, endDate]),
            returnValue: _i6.Future<List<_i3.Requirement>>.value(
              <_i3.Requirement>[],
            ),
          )
          as _i6.Future<List<_i3.Requirement>>);

  @override
  _i6.Future<void> setRequirements(List<_i3.RequirementUpdate>? requirements) =>
      (super.noSuchMethod(
            Invocation.method(#setRequirements, [requirements]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i3.ScheduleEntry>> getManagerSchedule(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getManagerSchedule, [startDate, endDate]),
            returnValue: _i6.Future<List<_i3.ScheduleEntry>>.value(
              <_i3.ScheduleEntry>[],
            ),
          )
          as _i6.Future<List<_i3.ScheduleEntry>>);

  @override
  _i6.Future<List<_i3.EmployeeScheduleEntry>> getEmployeeSchedule(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEmployeeSchedule, [startDate, endDate]),
            returnValue: _i6.Future<List<_i3.EmployeeScheduleEntry>>.value(
              <_i3.EmployeeScheduleEntry>[],
            ),
          )
          as _i6.Future<List<_i3.EmployeeScheduleEntry>>);

  @override
  _i6.Future<List<_i3.ScheduleEntry>> getTeamSchedule(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTeamSchedule, [startDate, endDate]),
            returnValue: _i6.Future<List<_i3.ScheduleEntry>>.value(
              <_i3.ScheduleEntry>[],
            ),
          )
          as _i6.Future<List<_i3.ScheduleEntry>>);

  @override
  _i6.Future<bool> isLoggedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isLoggedIn, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<List<_i3.TeamMember>> getUsers({bool? includeInactive = false}) =>
      (super.noSuchMethod(
            Invocation.method(#getUsers, [], {
              #includeInactive: includeInactive,
            }),
            returnValue: _i6.Future<List<_i3.TeamMember>>.value(
              <_i3.TeamMember>[],
            ),
          )
          as _i6.Future<List<_i3.TeamMember>>);

  @override
  _i6.Future<void> setUserRoles(String? userId, List<int>? roleIds) =>
      (super.noSuchMethod(
            Invocation.method(#setUserRoles, [userId, roleIds]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> resetUserPassword(String? userId, String? newPassword) =>
      (super.noSuchMethod(
            Invocation.method(#resetUserPassword, [userId, newPassword]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateUser(
    String? userId, {
    String? fullName,
    String? email,
    String? roleSystem,
    int? targetHoursPerMonth,
    int? targetShiftsPerMonth,
    bool? isActive,
    bool? clearTargets = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateUser,
              [userId],
              {
                #fullName: fullName,
                #email: email,
                #roleSystem: roleSystem,
                #targetHoursPerMonth: targetHoursPerMonth,
                #targetShiftsPerMonth: targetShiftsPerMonth,
                #isActive: isActive,
                #clearTargets: clearTargets,
              },
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> createUser({
    required String? username,
    required String? password,
    required String? fullName,
    required String? roleSystem,
    String? email,
    int? targetHoursPerMonth,
    int? targetShiftsPerMonth,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [], {
              #username: username,
              #password: password,
              #fullName: fullName,
              #roleSystem: roleSystem,
              #email: email,
              #targetHoursPerMonth: targetHoursPerMonth,
              #targetShiftsPerMonth: targetShiftsPerMonth,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> createAssignment({
    required DateTime? date,
    required int? shiftDefId,
    required String? userId,
    required int? roleId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createAssignment, [], {
              #date: date,
              #shiftDefId: shiftDefId,
              #userId: userId,
              #roleId: roleId,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteAssignment(String? scheduleId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAssignment, [scheduleId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteRole(int? roleId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRole, [roleId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteShift(int? shiftId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteShift, [shiftId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> saveBatchSchedule(
    DateTime? startDate,
    DateTime? endDate,
    List<_i3.ScheduleEntry>? entries,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveBatchSchedule, [
              startDate,
              endDate,
              entries,
            ]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateRole(int? roleId, String? name, String? colorHex) =>
      (super.noSuchMethod(
            Invocation.method(#updateRole, [roleId, name, colorHex]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateShift(
    int? shiftId,
    String? name,
    String? startTime,
    String? endTime,
    List<int>? applicableDays,
    List<int>? allowedRoleIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateShift, [
              shiftId,
              name,
              startTime,
              endTime,
              applicableDays,
              allowedRoleIds,
            ]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<Map<String, dynamic>> getAdminSettings() =>
      (super.noSuchMethod(
            Invocation.method(#getAdminSettings, []),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> updateAdminSettings({
    bool? isLoginEnabled,
    String? blockedLoginMessage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateAdminSettings, [], {
              #isLoginEnabled: isLoginEnabled,
              #blockedLoginMessage: blockedLoginMessage,
            }),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> updateAppSettings(
    Map<String, dynamic>? settings,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateAppSettings, [settings]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<void> registerDeviceToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#registerDeviceToken, [token]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> unregisterDeviceToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#unregisterDeviceToken, [token]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i3.AppNotification>> getNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#getNotifications, []),
            returnValue: _i6.Future<List<_i3.AppNotification>>.value(
              <_i3.AppNotification>[],
            ),
          )
          as _i6.Future<List<_i3.AppNotification>>);

  @override
  _i6.Future<void> markNotificationRead(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#markNotificationRead, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<Map<String, dynamic>> getConfig() =>
      (super.noSuchMethod(
            Invocation.method(#getConfig, []),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<void> saveConfig(
    String? name,
    String? openingHours,
    String? address, {
    bool? posEnabled,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #saveConfig,
              [name, openingHours, address],
              {#posEnabled: posEnabled},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i3.TeamAvailability>> getTeamAvailability(
    DateTime? weekStart,
    DateTime? weekEnd,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTeamAvailability, [weekStart, weekEnd]),
            returnValue: _i6.Future<List<_i3.TeamAvailability>>.value(
              <_i3.TeamAvailability>[],
            ),
          )
          as _i6.Future<List<_i3.TeamAvailability>>);

  @override
  _i6.Future<Map<String, dynamic>> getAttendanceDefaults(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#getAttendanceDefaults, [date]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> registerAttendance(
    DateTime? date,
    String? checkIn,
    String? checkOut,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#registerAttendance, [date, checkIn, checkOut]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<void> registerManualAttendance({
    required String? userId,
    required DateTime? date,
    required String? checkIn,
    required String? checkOut,
    bool? wasScheduled = true,
    String? status = 'CONFIRMED',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registerManualAttendance, [], {
              #userId: userId,
              #date: date,
              #checkIn: checkIn,
              #checkOut: checkOut,
              #wasScheduled: wasScheduled,
              #status: status,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getMyAttendance(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMyAttendance, [startDate, endDate]),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getPendingAttendance() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingAttendance, []),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<void> confirmAttendance(String? attendanceId) =>
      (super.noSuchMethod(
            Invocation.method(#confirmAttendance, [attendanceId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> rejectAttendance(String? attendanceId) =>
      (super.noSuchMethod(
            Invocation.method(#rejectAttendance, [attendanceId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getAllAttendance(
    DateTime? startDate,
    DateTime? endDate, {
    String? status,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getAllAttendance,
              [startDate, endDate],
              {#status: status},
            ),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<String?> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  String getAttendanceExportUrl(
    DateTime? startDate,
    DateTime? endDate, {
    String? status,
    String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getAttendanceExportUrl,
              [startDate, endDate],
              {#status: status, #token: token},
            ),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(
                #getAttendanceExportUrl,
                [startDate, endDate],
                {#status: status, #token: token},
              ),
            ),
          )
          as String);

  @override
  _i6.Future<List<Map<String, dynamic>>> getEmployeeHours(
    int? month,
    int? year,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEmployeeHours, [month, year]),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<_i3.UserStats> getUserStats(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserStats, [userId]),
            returnValue: _i6.Future<_i3.UserStats>.value(
              _FakeUserStats_4(
                this,
                Invocation.method(#getUserStats, [userId]),
              ),
            ),
          )
          as _i6.Future<_i3.UserStats>);

  @override
  _i6.Future<_i3.DashboardHome> getDashboardHome({DateTime? date}) =>
      (super.noSuchMethod(
            Invocation.method(#getDashboardHome, [], {#date: date}),
            returnValue: _i6.Future<_i3.DashboardHome>.value(
              _FakeDashboardHome_5(
                this,
                Invocation.method(#getDashboardHome, [], {#date: date}),
              ),
            ),
          )
          as _i6.Future<_i3.DashboardHome>);

  @override
  _i6.Future<List<_i3.ShiftGiveaway>> getGiveaways() =>
      (super.noSuchMethod(
            Invocation.method(#getGiveaways, []),
            returnValue: _i6.Future<List<_i3.ShiftGiveaway>>.value(
              <_i3.ShiftGiveaway>[],
            ),
          )
          as _i6.Future<List<_i3.ShiftGiveaway>>);

  @override
  _i6.Future<void> reassignGiveaway(String? giveawayId, String? newUserId) =>
      (super.noSuchMethod(
            Invocation.method(#reassignGiveaway, [giveawayId, newUserId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> cancelGiveaway(String? giveawayId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelGiveaway, [giveawayId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<Map<String, dynamic>> submitBugReport({
    required String? title,
    required String? description,
    String? steps = '',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#submitBugReport, [], {
              #title: title,
              #description: description,
              #steps: steps,
            }),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<void> giveAwayShift(String? scheduleId) =>
      (super.noSuchMethod(
            Invocation.method(#giveAwayShift, [scheduleId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<Map<String, dynamic>> getGoogleCalendarStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getGoogleCalendarStatus, []),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<void> connectGoogleCalendar(String? authCode) =>
      (super.noSuchMethod(
            Invocation.method(#connectGoogleCalendar, [authCode]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> disconnectGoogleCalendar() =>
      (super.noSuchMethod(
            Invocation.method(#disconnectGoogleCalendar, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<Map<String, dynamic>> syncGoogleCalendar() =>
      (super.noSuchMethod(
            Invocation.method(#syncGoogleCalendar, []),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<List<_i3.LeaveRequest>> getMyLeaveRequests({String? status}) =>
      (super.noSuchMethod(
            Invocation.method(#getMyLeaveRequests, [], {#status: status}),
            returnValue: _i6.Future<List<_i3.LeaveRequest>>.value(
              <_i3.LeaveRequest>[],
            ),
          )
          as _i6.Future<List<_i3.LeaveRequest>>);

  @override
  _i6.Future<void> createLeaveRequest(
    DateTime? startDate,
    DateTime? endDate,
    String? reason,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createLeaveRequest, [
              startDate,
              endDate,
              reason,
            ]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> cancelLeaveRequest(String? requestId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelLeaveRequest, [requestId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i3.LeaveRequest>> getAllLeaveRequests({String? status}) =>
      (super.noSuchMethod(
            Invocation.method(#getAllLeaveRequests, [], {#status: status}),
            returnValue: _i6.Future<List<_i3.LeaveRequest>>.value(
              <_i3.LeaveRequest>[],
            ),
          )
          as _i6.Future<List<_i3.LeaveRequest>>);

  @override
  _i6.Future<void> approveLeaveRequest(String? requestId) =>
      (super.noSuchMethod(
            Invocation.method(#approveLeaveRequest, [requestId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> rejectLeaveRequest(String? requestId) =>
      (super.noSuchMethod(
            Invocation.method(#rejectLeaveRequest, [requestId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i3.LeaveCalendarEntry>> getLeaveCalendar(
    int? year,
    int? month,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLeaveCalendar, [year, month]),
            returnValue: _i6.Future<List<_i3.LeaveCalendarEntry>>.value(
              <_i3.LeaveCalendarEntry>[],
            ),
          )
          as _i6.Future<List<_i3.LeaveCalendarEntry>>);

  @override
  _i6.Future<List<_i3.AvailableEmployee>> getAvailableEmployeesForShift(
    DateTime? date,
    int? shiftDefId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableEmployeesForShift, [
              date,
              shiftDefId,
            ]),
            returnValue: _i6.Future<List<_i3.AvailableEmployee>>.value(
              <_i3.AvailableEmployee>[],
            ),
          )
          as _i6.Future<List<_i3.AvailableEmployee>>);

  @override
  _i6.Future<Map<String, dynamic>> getScheduleSummary({
    required int? year,
    required int? month,
    required DateTime? weekStart,
    required DateTime? weekEnd,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getScheduleSummary, [], {
              #year: year,
              #month: month,
              #weekStart: weekStart,
              #weekEnd: weekEnd,
            }),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getEmployeeGiveaways() =>
      (super.noSuchMethod(
            Invocation.method(#getEmployeeGiveaways, []),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<void> claimGiveaway(String? giveawayId) =>
      (super.noSuchMethod(
            Invocation.method(#claimGiveaway, [giveawayId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i3.RestaurantTable>> getTables({
    bool? includeInactive = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTables, [], {
              #includeInactive: includeInactive,
            }),
            returnValue: _i6.Future<List<_i3.RestaurantTable>>.value(
              <_i3.RestaurantTable>[],
            ),
          )
          as _i6.Future<List<_i3.RestaurantTable>>);

  @override
  _i6.Future<_i3.RestaurantTable> createTable(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#createTable, [name]),
            returnValue: _i6.Future<_i3.RestaurantTable>.value(
              _FakeRestaurantTable_6(
                this,
                Invocation.method(#createTable, [name]),
              ),
            ),
          )
          as _i6.Future<_i3.RestaurantTable>);

  @override
  _i6.Future<void> deleteTable(String? tableId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTable, [tableId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i3.MenuItem>> getMenu({
    String? category,
    bool? includeInactive = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMenu, [], {
              #category: category,
              #includeInactive: includeInactive,
            }),
            returnValue: _i6.Future<List<_i3.MenuItem>>.value(<_i3.MenuItem>[]),
          )
          as _i6.Future<List<_i3.MenuItem>>);

  @override
  _i6.Future<_i3.MenuItem> createMenuItem(
    String? name,
    double? price,
    String? category,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createMenuItem, [name, price, category]),
            returnValue: _i6.Future<_i3.MenuItem>.value(
              _FakeMenuItem_7(
                this,
                Invocation.method(#createMenuItem, [name, price, category]),
              ),
            ),
          )
          as _i6.Future<_i3.MenuItem>);

  @override
  _i6.Future<_i3.MenuItem> updateMenuItem(
    String? itemId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateMenuItem, [itemId, data]),
            returnValue: _i6.Future<_i3.MenuItem>.value(
              _FakeMenuItem_7(
                this,
                Invocation.method(#updateMenuItem, [itemId, data]),
              ),
            ),
          )
          as _i6.Future<_i3.MenuItem>);

  @override
  _i6.Future<void> deleteMenuItem(String? itemId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMenuItem, [itemId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i3.KitchenOrder> createOrder(
    String? tableId,
    List<Map<String, dynamic>>? items,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createOrder, [tableId, items]),
            returnValue: _i6.Future<_i3.KitchenOrder>.value(
              _FakeKitchenOrder_8(
                this,
                Invocation.method(#createOrder, [tableId, items]),
              ),
            ),
          )
          as _i6.Future<_i3.KitchenOrder>);

  @override
  _i6.Future<List<_i3.KitchenOrder>> getOrders({
    String? tableId,
    String? status,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOrders, [], {
              #tableId: tableId,
              #status: status,
            }),
            returnValue: _i6.Future<List<_i3.KitchenOrder>>.value(
              <_i3.KitchenOrder>[],
            ),
          )
          as _i6.Future<List<_i3.KitchenOrder>>);

  @override
  _i6.Future<_i3.KitchenOrder> updateOrderStatus(
    String? orderId,
    String? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrderStatus, [orderId, status]),
            returnValue: _i6.Future<_i3.KitchenOrder>.value(
              _FakeKitchenOrder_8(
                this,
                Invocation.method(#updateOrderStatus, [orderId, status]),
              ),
            ),
          )
          as _i6.Future<_i3.KitchenOrder>);

  @override
  _i6.Future<_i3.KitchenOrder> cancelOrder(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelOrder, [orderId]),
            returnValue: _i6.Future<_i3.KitchenOrder>.value(
              _FakeKitchenOrder_8(
                this,
                Invocation.method(#cancelOrder, [orderId]),
              ),
            ),
          )
          as _i6.Future<_i3.KitchenOrder>);

  @override
  _i6.Future<List<_i3.TableZone>> getZones() =>
      (super.noSuchMethod(
            Invocation.method(#getZones, []),
            returnValue: _i6.Future<List<_i3.TableZone>>.value(
              <_i3.TableZone>[],
            ),
          )
          as _i6.Future<List<_i3.TableZone>>);

  @override
  _i6.Future<_i3.TableZone> createZone(String? name, {int? sortOrder = 0}) =>
      (super.noSuchMethod(
            Invocation.method(#createZone, [name], {#sortOrder: sortOrder}),
            returnValue: _i6.Future<_i3.TableZone>.value(
              _FakeTableZone_9(
                this,
                Invocation.method(#createZone, [name], {#sortOrder: sortOrder}),
              ),
            ),
          )
          as _i6.Future<_i3.TableZone>);

  @override
  _i6.Future<List<_i3.PosTable>> getTablesV2({
    String? zoneId,
    String? status,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTablesV2, [], {
              #zoneId: zoneId,
              #status: status,
            }),
            returnValue: _i6.Future<List<_i3.PosTable>>.value(<_i3.PosTable>[]),
          )
          as _i6.Future<List<_i3.PosTable>>);

  @override
  _i6.Future<_i3.PosTable> createTableV2(
    String? name, {
    String? zoneId,
    int? seats = 4,
    int? sortOrder = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createTableV2,
              [name],
              {#zoneId: zoneId, #seats: seats, #sortOrder: sortOrder},
            ),
            returnValue: _i6.Future<_i3.PosTable>.value(
              _FakePosTable_10(
                this,
                Invocation.method(
                  #createTableV2,
                  [name],
                  {#zoneId: zoneId, #seats: seats, #sortOrder: sortOrder},
                ),
              ),
            ),
          )
          as _i6.Future<_i3.PosTable>);

  @override
  _i6.Future<_i3.PosTable> updateTableV2(
    String? tableId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateTableV2, [tableId, data]),
            returnValue: _i6.Future<_i3.PosTable>.value(
              _FakePosTable_10(
                this,
                Invocation.method(#updateTableV2, [tableId, data]),
              ),
            ),
          )
          as _i6.Future<_i3.PosTable>);

  @override
  _i6.Future<List<_i3.PosCategory>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i6.Future<List<_i3.PosCategory>>.value(
              <_i3.PosCategory>[],
            ),
          )
          as _i6.Future<List<_i3.PosCategory>>);

  @override
  _i6.Future<_i3.PosCategory> createCategory(
    String? name, {
    String? colorHex = '#607D8B',
    String? iconName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createCategory,
              [name],
              {#colorHex: colorHex, #iconName: iconName},
            ),
            returnValue: _i6.Future<_i3.PosCategory>.value(
              _FakePosCategory_11(
                this,
                Invocation.method(
                  #createCategory,
                  [name],
                  {#colorHex: colorHex, #iconName: iconName},
                ),
              ),
            ),
          )
          as _i6.Future<_i3.PosCategory>);

  @override
  _i6.Future<_i3.PosCategory> updateCategory(
    int? categoryId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateCategory, [categoryId, data]),
            returnValue: _i6.Future<_i3.PosCategory>.value(
              _FakePosCategory_11(
                this,
                Invocation.method(#updateCategory, [categoryId, data]),
              ),
            ),
          )
          as _i6.Future<_i3.PosCategory>);

  @override
  _i6.Future<List<_i3.PosMenuItem>> getMenuV2({int? categoryId}) =>
      (super.noSuchMethod(
            Invocation.method(#getMenuV2, [], {#categoryId: categoryId}),
            returnValue: _i6.Future<List<_i3.PosMenuItem>>.value(
              <_i3.PosMenuItem>[],
            ),
          )
          as _i6.Future<List<_i3.PosMenuItem>>);

  @override
  _i6.Future<_i3.PosMenuItem> createMenuItemV2(
    String? name,
    double? price,
    int? categoryId, {
    String? description,
    double? taxRate = 0.23,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createMenuItemV2,
              [name, price, categoryId],
              {#description: description, #taxRate: taxRate},
            ),
            returnValue: _i6.Future<_i3.PosMenuItem>.value(
              _FakePosMenuItem_12(
                this,
                Invocation.method(
                  #createMenuItemV2,
                  [name, price, categoryId],
                  {#description: description, #taxRate: taxRate},
                ),
              ),
            ),
          )
          as _i6.Future<_i3.PosMenuItem>);

  @override
  _i6.Future<_i3.PosMenuItem> updateMenuItemV2(
    String? itemId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateMenuItemV2, [itemId, data]),
            returnValue: _i6.Future<_i3.PosMenuItem>.value(
              _FakePosMenuItem_12(
                this,
                Invocation.method(#updateMenuItemV2, [itemId, data]),
              ),
            ),
          )
          as _i6.Future<_i3.PosMenuItem>);

  @override
  _i6.Future<List<_i3.ModifierGroup>> getModifierGroups() =>
      (super.noSuchMethod(
            Invocation.method(#getModifierGroups, []),
            returnValue: _i6.Future<List<_i3.ModifierGroup>>.value(
              <_i3.ModifierGroup>[],
            ),
          )
          as _i6.Future<List<_i3.ModifierGroup>>);

  @override
  _i6.Future<_i3.ModifierGroup> createModifierGroup(
    String? name, {
    int? minSelect = 0,
    int? maxSelect = 1,
    List<Map<String, dynamic>>? modifiers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createModifierGroup,
              [name],
              {
                #minSelect: minSelect,
                #maxSelect: maxSelect,
                #modifiers: modifiers,
              },
            ),
            returnValue: _i6.Future<_i3.ModifierGroup>.value(
              _FakeModifierGroup_13(
                this,
                Invocation.method(
                  #createModifierGroup,
                  [name],
                  {
                    #minSelect: minSelect,
                    #maxSelect: maxSelect,
                    #modifiers: modifiers,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i3.ModifierGroup>);

  @override
  _i6.Future<void> linkModifierGroup(String? itemId, int? groupId) =>
      (super.noSuchMethod(
            Invocation.method(#linkModifierGroup, [itemId, groupId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i3.PosOrder> createOrderV2(
    String? tableId,
    List<Map<String, dynamic>>? items, {
    int? guestCount = 1,
    String? notes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createOrderV2,
              [tableId, items],
              {#guestCount: guestCount, #notes: notes},
            ),
            returnValue: _i6.Future<_i3.PosOrder>.value(
              _FakePosOrder_14(
                this,
                Invocation.method(
                  #createOrderV2,
                  [tableId, items],
                  {#guestCount: guestCount, #notes: notes},
                ),
              ),
            ),
          )
          as _i6.Future<_i3.PosOrder>);

  @override
  _i6.Future<List<_i3.PosOrder>> getOrdersV2({
    String? tableId,
    String? status,
    String? waiterId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOrdersV2, [], {
              #tableId: tableId,
              #status: status,
              #waiterId: waiterId,
            }),
            returnValue: _i6.Future<List<_i3.PosOrder>>.value(<_i3.PosOrder>[]),
          )
          as _i6.Future<List<_i3.PosOrder>>);

  @override
  _i6.Future<_i3.PosOrder> getOrderV2(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#getOrderV2, [orderId]),
            returnValue: _i6.Future<_i3.PosOrder>.value(
              _FakePosOrder_14(this, Invocation.method(#getOrderV2, [orderId])),
            ),
          )
          as _i6.Future<_i3.PosOrder>);

  @override
  _i6.Future<_i3.PosOrder> addItemsToOrder(
    String? orderId,
    List<Map<String, dynamic>>? items,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addItemsToOrder, [orderId, items]),
            returnValue: _i6.Future<_i3.PosOrder>.value(
              _FakePosOrder_14(
                this,
                Invocation.method(#addItemsToOrder, [orderId, items]),
              ),
            ),
          )
          as _i6.Future<_i3.PosOrder>);

  @override
  _i6.Future<_i3.PosOrder> updateOrderStatusV2(
    String? orderId,
    String? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrderStatusV2, [orderId, status]),
            returnValue: _i6.Future<_i3.PosOrder>.value(
              _FakePosOrder_14(
                this,
                Invocation.method(#updateOrderStatusV2, [orderId, status]),
              ),
            ),
          )
          as _i6.Future<_i3.PosOrder>);

  @override
  _i6.Future<_i3.PosOrder> applyDiscount(
    String? orderId,
    double? discountPct,
    String? managerPin,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#applyDiscount, [
              orderId,
              discountPct,
              managerPin,
            ]),
            returnValue: _i6.Future<_i3.PosOrder>.value(
              _FakePosOrder_14(
                this,
                Invocation.method(#applyDiscount, [
                  orderId,
                  discountPct,
                  managerPin,
                ]),
              ),
            ),
          )
          as _i6.Future<_i3.PosOrder>);

  @override
  _i6.Future<_i3.PosOrderItem> updateKdsItemStatus(
    String? itemId,
    String? kdsStatus,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateKdsItemStatus, [itemId, kdsStatus]),
            returnValue: _i6.Future<_i3.PosOrderItem>.value(
              _FakePosOrderItem_15(
                this,
                Invocation.method(#updateKdsItemStatus, [itemId, kdsStatus]),
              ),
            ),
          )
          as _i6.Future<_i3.PosOrderItem>);

  @override
  _i6.Future<List<dynamic>> getKdsItems({String? status}) =>
      (super.noSuchMethod(
            Invocation.method(#getKdsItems, [], {#status: status}),
            returnValue: _i6.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i6.Future<List<dynamic>>);

  @override
  _i6.Future<_i3.PosPayment> createPayment(
    String? orderId,
    String? method,
    double? amount, {
    double? tipAmount = 0.0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createPayment,
              [orderId, method, amount],
              {#tipAmount: tipAmount},
            ),
            returnValue: _i6.Future<_i3.PosPayment>.value(
              _FakePosPayment_16(
                this,
                Invocation.method(
                  #createPayment,
                  [orderId, method, amount],
                  {#tipAmount: tipAmount},
                ),
              ),
            ),
          )
          as _i6.Future<_i3.PosPayment>);

  @override
  _i6.Future<_i3.TipSummary> getMyTips({String? date}) =>
      (super.noSuchMethod(
            Invocation.method(#getMyTips, [], {#date: date}),
            returnValue: _i6.Future<_i3.TipSummary>.value(
              _FakeTipSummary_17(
                this,
                Invocation.method(#getMyTips, [], {#date: date}),
              ),
            ),
          )
          as _i6.Future<_i3.TipSummary>);
}
