"""add_user_monthly_targets

Revision ID: 1c2a74aa2b86
Revises: 876041b12da9
Create Date: 2026-02-10 18:13:09.460353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1c2a74aa2b86'
down_revision: Union[str, None] = '876041b12da9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('target_hours_per_month', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('target_shifts_per_month', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'target_shifts_per_month')
    op.drop_column('user', 'target_hours_per_month')
    # ### end Alembic commands ###
