"""flexible_staffing_features

Revision ID: 876041b12da9
Revises: 003_add_applicable_days
Create Date: 2026-02-10 18:07:50.187262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '876041b12da9'
down_revision: Union[str, None] = '003_add_applicable_days'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staffingrequirement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_of_week', sa.Integer(), nullable=True))
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staffingrequirement', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.drop_column('day_of_week')
    # ### end Alembic commands ###
