"""BCNF Normalization

Revision ID: f55dfe5e9e52
Revises: 3281399c43e4
Create Date: 2026-02-27 02:44:00.433609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f55dfe5e9e52'
down_revision: Union[str, None] = '3281399c43e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurantopeninghour',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=False),
    sa.Column('close_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['restaurantconfig.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shiftdefinitiondaylink',
    sa.Column('shift_def_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shift_def_id'], ['shiftdefinition.id'], ),
    sa.PrimaryKeyConstraint('shift_def_id', 'day_of_week')
    )
    op.drop_column('restaurantconfig', 'opening_hours')
    op.drop_column('shiftdefinition', 'applicable_days')
    op.add_column('user', sa.Column('encrypted_google_access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('encrypted_google_refresh_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('user', 'google_refresh_token')
    op.drop_column('user', 'google_access_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('google_access_token', sa.VARCHAR(), nullable=True))
    op.add_column('user', sa.Column('google_refresh_token', sa.VARCHAR(), nullable=True))
    op.drop_column('user', 'encrypted_google_refresh_token')
    op.drop_column('user', 'encrypted_google_access_token')
    op.add_column('shiftdefinition', sa.Column('applicable_days', sa.VARCHAR(), nullable=False))
    op.add_column('restaurantconfig', sa.Column('opening_hours', sa.VARCHAR(), nullable=False))
    op.drop_table('shiftdefinitiondaylink')
    op.drop_table('restaurantopeninghour')
    # ### end Alembic commands ###
