"""add_leave_requests_and_leavestate

Revision ID: 67755cb4eaa5
Revises: b7dde36bea9d
Create Date: 2026-02-24 17:31:49.817141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '67755cb4eaa5'
down_revision: Union[str, None] = 'b7dde36bea9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    if not conn.dialect.has_table(conn, 'leaverequest'):
        op.create_table('leaverequest',
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('user_id', sa.Uuid(), nullable=False),
            sa.Column('start_date', sa.Date(), nullable=False),
            sa.Column('end_date', sa.Date(), nullable=False),
            sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='leavestatus'), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('reviewed_at', sa.DateTime(), nullable=True),
            sa.Column('reviewed_by', sa.Uuid(), nullable=True),
            sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], ),
            sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leaverequest')
    # ### end Alembic commands ###
