"""Add Notification table

Revision ID: 285d42f5464a
Revises: 67755cb4eaa5
Create Date: 2026-02-26 04:08:02.916072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '285d42f5464a'
down_revision: Union[str, None] = '67755cb4eaa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    
    with op.batch_alter_table('leaverequest') as batch_op:
        batch_op.alter_column('reason',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
        batch_op.create_index(batch_op.f('ix_leaverequest_user_id'), ['user_id'], unique=False)
        
    with op.batch_alter_table('user') as batch_op:
        batch_op.alter_column('manager_pin',
                   existing_type=sa.TEXT(),
                   type_=sqlmodel.sql.sqltypes.AutoString(),
                   existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'manager_pin',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_leaverequest_user_id'), table_name='leaverequest')
    op.alter_column('leaverequest', 'reason',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_table('notification')
    # ### end Alembic commands ###
