"""Add UserDevice for FCM tokens

Revision ID: 3281399c43e4
Revises: 285d42f5464a
Create Date: 2026-02-27 01:06:28.716618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3281399c43e4'
down_revision: Union[str, None] = '285d42f5464a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userdevice',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('fcm_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_active', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userdevice_fcm_token'), 'userdevice', ['fcm_token'], unique=True)
    op.create_index(op.f('ix_userdevice_user_id'), 'userdevice', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userdevice_user_id'), table_name='userdevice')
    op.drop_index(op.f('ix_userdevice_fcm_token'), table_name='userdevice')
    op.drop_table('userdevice')
    # ### end Alembic commands ###
