"""add_menu_item_name_snapshot

Revision ID: 0fb76fb496a6
Revises: a6fcb307b602
Create Date: 2026-03-22 16:36:59.776786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0fb76fb496a6'
down_revision: Union[str, None] = 'a6fcb307b602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    # Check for kitchenorderitem columns
    if 'kitchenorderitem' in inspector.get_table_names():
        kitchenorderitem_columns = [c['name'] for c in inspector.get_columns('kitchenorderitem')]
        if 'menu_item_name_snapshot' not in kitchenorderitem_columns:
            op.add_column('kitchenorderitem', sa.Column('menu_item_name_snapshot', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    else:
        op.add_column('kitchenorderitem', sa.Column('menu_item_name_snapshot', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # Check for user columns
    if 'user' in inspector.get_table_names():
        user_columns = [c['name'] for c in inspector.get_columns('user')]
        if 'google_access_token' in user_columns:
            op.drop_column('user', 'google_access_token')
        if 'google_refresh_token' in user_columns:
            op.drop_column('user', 'google_refresh_token')
    else:
        op.drop_column('user', 'google_access_token')
        op.drop_column('user', 'google_refresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if 'user' in inspector.get_table_names():
        user_columns = [c['name'] for c in inspector.get_columns('user')]
        if 'google_refresh_token' not in user_columns:
            op.add_column('user', sa.Column('google_refresh_token', sa.VARCHAR(), nullable=True))
        if 'google_access_token' not in user_columns:
            op.add_column('user', sa.Column('google_access_token', sa.VARCHAR(), nullable=True))

    if 'kitchenorderitem' in inspector.get_table_names():
        kitchenorderitem_columns = [c['name'] for c in inspector.get_columns('kitchenorderitem')]
        if 'menu_item_name_snapshot' in kitchenorderitem_columns:
            op.drop_column('kitchenorderitem', 'menu_item_name_snapshot')
    # ### end Alembic commands ###
