"""add_menu_item_name_snapshot

Revision ID: 0fb76fb496a6
Revises: a6fcb307b602
Create Date: 2026-03-22 16:36:59.776786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0fb76fb496a6'
down_revision: Union[str, None] = 'a6fcb307b602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kitchenorderitem', sa.Column('menu_item_name_snapshot', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('user', 'google_access_token')
    op.drop_column('user', 'google_refresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('google_refresh_token', sa.VARCHAR(), nullable=True))
    op.add_column('user', sa.Column('google_access_token', sa.VARCHAR(), nullable=True))
    op.drop_column('kitchenorderitem', 'menu_item_name_snapshot')
    # ### end Alembic commands ###
