// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzP9MzJHrPihaq7P20vpWMdAf_6IJ93qI',
    appId: '1:357153331477:web:3593c50a84a8e0c7ba711c',
    messagingSenderId: '357153331477',
    projectId: 'planista-e31fe',
    authDomain: 'planista-e31fe.firebaseapp.com',
    storageBucket: 'planista-e31fe.firebasestorage.app',
    measurementId: 'G-HKRM635THK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ3dUVx3LQiSRowSsEYpZ2-U0fnuJyPVU',
    appId: '1:357153331477:android:6e27d5059aa13a5fba711c',
    messagingSenderId: '357153331477',
    projectId: 'planista-e31fe',
    storageBucket: 'planista-e31fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6OZf1USzX5TPIeBgMA9yfVDwU2YG3-WQ',
    appId: '1:357153331477:ios:e28b4bcbf45d1700ba711c',
    messagingSenderId: '357153331477',
    projectId: 'planista-e31fe',
    storageBucket: 'planista-e31fe.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );
}
