// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjR-UzMDIg5LyySkJU_ZvZVM3gfQLyApo',
    appId: '1:574490637423:web:af31c1516c6caf63dd099a',
    messagingSenderId: '574490637423',
    projectId: 'planista-dev',
    authDomain: 'planista-dev.firebaseapp.com',
    storageBucket: 'planista-dev.firebasestorage.app',
    measurementId: 'G-ZY5L6GEBBR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCow5Juy8GZFhxjpms6ei1kBOkbis4QV0o',
    appId: '1:574490637423:android:8fed494488c79045dd099a',
    messagingSenderId: '574490637423',
    projectId: 'planista-dev',
    storageBucket: 'planista-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFeAHpdqT8LUWol3I03hfeF0rHN4QrjXg',
    appId: '1:574490637423:ios:cad5c97e3c8642e7dd099a',
    messagingSenderId: '574490637423',
    projectId: 'planista-dev',
    storageBucket: 'planista-dev.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );
}
